### ISSUE TITLE
Add support for Port Assignment

### ISSUE THREAD

**Issue by hasheddan** [hasheddan/stack-packet-demo#16]
### What problem are you facing?

`crossplane-provider-packet` does not currently have support for assigning ports to virtual networks

### How could the Packet Crossplane Provider help solve your problem?

Add `v1alpha1` support for `Assignment` in `ports.packet.crossplane.io` group.

**Comment by hasheddan** [comment]
@displague could you sign off my chosen GVK for this resources and #15?

**Comment by displague** [comment]
In terms of the API, there is more than one "Assignment" type that can be imagined for "ports.packet.crossplane.io".

* https://www.packet.com/developers/api/ports/#ports-assignPort
* https://www.packet.com/developers/api/ports/#ports-assignNativeVlan

[Terraform `packet_port_vlan_attachment`](https://www.terraform.io/docs/providers/packet/r/port_vlan_attachment.html#argument-reference) exposes these two endpoints using a `native` parameter, and perhaps Crossplane can take the same approach (rather than creating two separate resource names).

`Attachment` is also an option, which maps to the Terraform provider naming. 

`Assignment` sounds good. We can change this in the PR if needed.

---

`Assignment` vs `Attachment` will come up again when visiting these API endpoints (likely others):
* https://www.packet.com/developers/api/ipaddresses/#ipaddresses-createIPAssignment
* https://www.packet.com/developers/api/vlans/#vlans-assignNativeVlan
