### ISSUE TITLE
Friendly project name vs. uuid?

### ISSUE THREAD

**Issue by prasek** [hasheddan/stack-packet-demo#4]
Is there an option to use the friendly project name vs. UUID?

![image](https://user-images.githubusercontent.com/284840/66947925-944d2880-f008-11e9-8c13-aecbc94ab631.png)

![image](https://user-images.githubusercontent.com/284840/66947744-4506f800-f008-11e9-9918-28b60d297730.png)

//cc @hasheddan

**Comment by prasek** [comment]
I know the project can be renamed, UUIDs are stable, and you can easily get the UUID from the project settings, but the rest of the fields in this are human readable, so the project_id is the only field that isn't human readable. Maybe this is more of an issue for Packet itself, if they supported GCP-style project ids this would work with that.

**Comment by jasmingacic** [comment]
@prasek What you are suggesting really makes sense. I can certainly pass this and see what can be done.

**Comment by hasheddan** [comment]
@prasek @jasmingacic one options could also be to have the `Provider` scoped to a certain project. We follow this pattern in [stack-gcp](https://github.com/crossplaneio/stack-gcp/blob/32c2999e25af12712aa811658c4526d084838944/apis/v1alpha2/types.go#L32) and I think it would make sense here as well.

**Comment by displague** [comment]
Thanks for reporting this @prasek !

I'm actually running into the same need in other tools. One complication with presenting project names is that the project names can overlap between organizations.  I've encountered this with projects named "Dev", for example, across numerous Packet organizations my account is a member of.

That said, I'm closing this because (like @hasheddan suggested) [v0.0.2](https://github.com/packethost/crossplane-provider-packet/releases/tag/v0.0.2) moved the `ProjectID` into the `Provider` (and also made it configurable through the provider secret as a fall-back).

https://gist.github.com/displague/cbed973ce8925fa94c8db1250c5deae9#file-0-packet-provider-yaml

Additionally, the latest `Device` resource shape does not include the ProjectID:

https://gist.github.com/displague/cbed973ce8925fa94c8db1250c5deae9#file-1-packet-device-yaml
